steps:
# Decrypt crypto key
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=.env.enc
  - --plaintext-file=.env
  - --location=gloabl
  - --keyring=myproject
  - --key=cloudbuild-env

# Install
- name: 'gcr.io/cloud-builders/yarn'
  args: ['install']

# Test
- name: 'gcr.io/cloud-builders/yarn'
  args: ['test:unit']

# Build
- name: 'gcr.io/cloud-builders/yarn'
  args: ['build']

# Deploy
- name: 'gcr.io/cloud-builders/yarn'
  args: ['deploy']